# -*- coding: utf-8 -*-
"""Big Tech Enterprises Map(Python Folium)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKEqGoAFzcW3s_3x3zhLJtQoauWYS5M7
"""

pip install folium

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv

!rm ~/.cache/matplotlib -rf

import pandas as pd
df=pd.read_csv("Big Tech enterprises Latitude Longitude and the names.csv",encoding="utf-8")
print(df)

pos=df[["위도 (Latitude)","경도 (Longitude)"]].values
print(pos)

import folium
map=folium.Map(location=[36.64,127.47],zoom_start=10, tiles="CartoDB positron")
# location: 기준 좌표 지정, zoom_start: 확대 정도 지정(1~18)
folium.Marker([36.64,127.47]).add_to(map)
# [위도, 경도] 지정 좌표에 마커를 추가
map.save("map1.html")

pos=df[["위도 (Latitude)","경도 (Longitude)"]].values
map=folium.Map(location=[37.524,126.977],zoom_start=12, tiles="CartoDB positron")
for data in pos:
  folium.Marker([data[0],data[1]]).add_to(map)
# 반복문을 이용하여 csv 내의 모든 [위도, 경도] 좌표에 마커를 추가
map.save("map2.html")

pos=df[["위도 (Latitude)","경도 (Longitude)","시설명"]].values
map=folium.Map(location=[37.524,126.977],zoom_start=12, tiles="CartoDB positron")
for data in pos:
  folium.Marker([data[0],data[1]],tooltip=data[2]).add_to(map)

map.save("map3.html")